---
title: "DSCI 522 Individual Assessment 1"
output: html_document
---

## Individual assignment 1

rubric={correctness:1}

The purpose of this assignment is to ensure that everyone does some self-learning and obtains practice on using docopt to create command line arguements in scripts, as well as creating releases on GitHub. This assignment will be graded for completion. You must attempt all questions to get the grade.

### Submission instructions

-   You should commit and push your changes to the public GitHub.com repository you created in exercise 1.
-   You should submit a `.html` version of this assignment to Canvas.

### Exercise 1

Create a public repository on GitHub.com called `docopt_demo`. Paste the url below:

> <https://github.com/YXIN15/docopt_demo>

### Exercise 2

**Getting documentation from a {docopt} R script**

In [this repo](https://github.ubc.ca/MDS-2022-23/DSCI_522_dsci-workflows_students), in the `src` directory, you will find a script named `demo.R`. Access the documentation for that script from the command line by running the script with the `--help` option (and no other options or arguments). Paste the documentation that was printed out to your terminal below.

>     $ Rscript demo.R --help
>     This script prints out docopt args.
>     Usage: demo.R <arg1> --arg2=<arg2> [--arg3=<arg3>]
>
>     Options:
>     <arg>             Takes any value (this is a required positional argument)
>     --arg2=<arg2>     Takes any value (this is a required option)
>     [--arg3=<arg3>]   Takes any value (this is an optional option) 

### Exercise 3

**What does `docopt` return in R?**

Run the `demo.R` script giving it appropriate arguments to see what the `docopt` function in R returns. Try setting and not setting a value for `arg3`. Describe what you observed below.

For options, you need to include the `--` in the command line call, for example:

    Rscript src/my_script something --anoption=something more

> It returns the parsed documentation in the script, which contains information about the arguments, and the values that were inputted for these arguments. In this case, it returns a named list with 6 items. The first 3 items are the values for the arguments, and are named in the way the arguments appear in the documentation, as in "\--arg2", "\--arg3", and \<arg1\>. It lists the named arguments first, and then positional arguments. The other three items again the values associated with the arguments, but this time they are simply named by the argument "arg2", "arg3" and "arg1". If we don't include a value for `arg3`, the values for "\--arg3" and "arg3" are both `NULL`.
>
> It also then returns `NULL` on a new line, and the type of the first output (i.e. "List")
>
> For example, the output without setting a value for `arg3` is as follows:
>
> `$ Rscript demo.R 1 --arg2=2`
>
> `List of 6`
>
> `$ --arg2: chr "2"`
>
> `$ --arg3: NULL`
>
> `$ <arg1>: chr "1"`
>
> `$ arg2  : chr "2"`
>
> `$ arg3  : NULL`
>
> `$ arg1  : chr "1"`
>
> `NULL`
>
> `[1] "list"`

### Exercise 4

**Break this script!**

Run the `demo.R` script and find at least 3 different ways to break it by changing the values or order of the command line arguments at the command line (do not modify the script). Document how you did this below.

> 1.  Add arguments that are not defined (i.e. `$ Rscript demo.R 1 --arg2=2 --arg_new=3`)
> 2.  Not adding a required argument (i.e. `$ Rscript demo.R 1`)
> 3.  Not using the proper "flags" (i.e. `$ Rscript demo.R 1 arg2=2`)

### Exercise 5

**Add a new optional positional argument**

Copy the `demo.R` script into your `docopt_demo` repo, and then edit it to add a new positional argument that is optional. Commit this change and push it to your `docopt_demo` repository. Paste the URL to this commit below:

> <https://github.com/YXIN15/docopt_demo/commit/7d42ab33cfadff9577036bcdfddecfbe97266e7f>

### Exercise 6

**Add a main function**

Modify the `demo.R` script further so that the print statements happen inside a main function. Commit this change and push it to your `docopt_demo` repository. Paste the URL to this commit below:

> <https://github.com/YXIN15/docopt_demo/commit/2533e424bb6395c99d5fa11334d4c957008c4cf9>

### Exercise 7

**What does `docopt` return in Python?**

In [this repo](https://github.ubc.ca/MDS-2022-23/DSCI_522_dsci-workflows_students), in the `src` directory, you will find a script named `demo.py`. Run the `demo.py` script giving it appropriate arguments to see what the `docopt` function in Python returns. Try setting and not setting a value for `arg3`. How does this differ from what `docopt` returns in R? Describe what you observed below.

> In python, rather than a named list like in R, we return a dictionary with arguments as keys and inputs as values. If we don't include a value for `arg3`, then its value in the dictionary is `None`. We also return the class `<class 'docopt.ParsedOptions'>` which is different than the `list` type returned by R.

### Exercise 8

**Add a new optional positional argument**

Copy the `demo.py` script into your `docopt_demo` repo, and then edit it to add a new positional argument that is optional. Commit this change and push it to your `docopt_demo` repository. Paste the URL to this commit below:

> <https://github.com/YXIN15/docopt_demo/commit/b6d75d0ef54db05045b08aef5a625391e57fd924>

### Exercise 9

Modify the `demo.py` script further so that the print statements happen inside a main function. Commit this change and push it to your `docopt_demo` repository. Paste the URL to this commit below:

> <https://github.com/YXIN15/docopt_demo/commit/565078b98b48cf6ff830ab1c7401be2e6945d8ea>

### Exercise 10

Create a release in your `docopt_demo` repo called `0.1.0`. Paste the URL to this release below.

\*Hint: See the [creating a release docs](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/managing-releases-in-a-repository#creating-a-release) to help complete this exercise.

> <https://github.com/YXIN15/docopt_demo/releases/tag/0.1.0>
